use std::fs::File;
use std::io::{self, Write};
use std::time::{SystemTime, UNIX_EPOCH};

#[derive(Debug)]
pub struct SecurityIncident {
    pub timestamp: u64,
    pub source_ip: String,
    pub destination_port: u16,
    pub event_type: String,
}

pub fn current_timestamp() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs()
}

pub fn save_report_txt(incident: &SecurityIncident) -> io::Result<()> {
    let report = format!(
r#"=== BESNICH SECURITY REPORT ===

Timestamp: {}
Source IP: {}
Destination Port: {}
Event Type: {}

Generated by:
Authority-Segnalation
"#,
        incident.timestamp,
        incident.source_ip,
        incident.destination_port,
        incident.event_type
    );

    let filename = format!("authority-report-{}.txt", incident.timestamp);

    let mut file = File::create(filename)?;
    file.write_all(report.as_bytes())?;

    Ok(())
}

pub enum UserDecision {
    Ignore,
    BlockIp,
    GenerateReport,
}

pub fn ask_user(incident: &SecurityIncident) -> UserDecision {
    println!(
        "\n[Authority-Segnalation]\n\
        Attività sospetta rilevata\n\
        IP: {}\n\
        Porta: {}\n\
        \n\
        1) Ignora\n\
        2) Blocca IP\n\
        3) Genera Report\n",
        incident.source_ip,
        incident.destination_port
    );

    let mut input = String::new();
    io::stdin().read_line(&mut input).unwrap();

    match input.trim() {
        "2" => UserDecision::BlockIp,
        "3" => UserDecision::GenerateReport,
        _ => UserDecision::Ignore,
    }
}
